// This file has been generated by Specta. DO NOT EDIT.

export type Hero = { title: string; description: string; button: string; background: string; author: string; appId: string }

export type DeveloperUser = { name: string; description: string; gh_username: string; icon_base64: string | null; ahq_official: boolean; email: string; support: AppSupport; apps: string[] }

export type InstallerOptionsWindows = { assetId: number; exec: string | null; scope: WindowsInstallScope | null; installerArgs: string[] | null }

export type Home = { splash: Splash | null; home: HomeMapData }

export type Semi = { title: string; background: string; appId: string; color: string | null }

export type SearchEntry = { name: string; title: string; id: string }

/**
 * 🔬 Under Development
 * 
 * 
 */
export type InstallerOptionsAndroid = { assetId: number; min_sdk: number; abi: AndroidAbi[] }

export type InstallerFormat = "WindowsZip" | "WindowsInstallerMsi" | "WindowsInstallerExe" | "WindowsUWPMsix" | "WindowsAHQDB" | "LinuxAppImage" | "AndroidApkZip"

/**
 * Use the official ahqstore (<https://crates.io/crates/ahqstore_cli_rs>) cli\n🎯 Introduced in v1, Revamped in v2
 */
export type AHQStoreApplication = { appId: string; appShortcutName: string; appDisplayName: string; authorId: string; releaseTagName: string; downloadUrls: { [key: number]: DownloadUrl }; install: InstallerOptions; displayImages: number[]; description: string; repo: AppRepo; usrVersion: string | null; version: number; site: string | null; source: string | null; license_or_tos: string | null; resources: { [key: number]: number[] } | null; verified: boolean }

export type AppUpdateInstallStatus = { status: "Pending" } | { status: "Cancelled" } | { status: "Downloading"; progress: number } | { status: "Installing" } | { status: "Updating" } | { status: "Uninstalling" } | { status: "Done" }

export type AppStatus = "Pending" | "Downloading" | "AVScanning" | "Installing" | "Uninstalling" | "InstallSuccessful" | "UninstallSuccessful" | "NotSuccessful" | "AVFlagged"

export type SubHero = { title: string; background: string; appId: string; color: string | null }

export type DevData = { name: string | null; id: string; github: string; avatar_url: string | null; verified?: boolean }

/**
 * PREFERENCES
 */
export type UpdateStrategy = "Never" | "CheckOnly" | "DownloadInstall_UnmeteredWifi" | "DownloadInstall_Wifi" | "DownloadInstall"

/**
 * **You should use cli**
 * ```sh
 * cargo install ahqstore_cli_rs
 * ```
 * or visit app / api sub module
 * 
 * This Module:
 * This module lists the standard commands & types that AHQ Store sends to AHQ Store Service
 */
export type StatusUpdateData = { queue: { id: string; status: AppUpdateInstallStatus }; supportsUpdate: boolean }

export type Commits = { ahqstore: string; alt: string }

/**
 * 🔬 Under Development
 * 
 * 
 */
export type AndroidAbi = "Aarch64" | "Armv7" | "X86" | "X64"

export type QueuedApp = { id: string; status: AppUpdateInstallStatus }

export type InstallerScheme = { PackageIdentifier: string; PackageVersion: string; Scope: string; Installers: Installer[] }

export type GHRepoCommit = { sha: string }

export type AppRepo = { author: string; repo: string }

/**
 * 🔬 Under Development
 * 
 * 
 */
export type InstallerOptionsLinux = { assetId: number }

export type AppSupport = { discord: string | null; website: string | null; github: string | null }

export type UpdateStatusReport = "Disabled" | "UpToDate" | "Checking" | "Updating"

export type InstallerOptions = { win32: InstallerOptionsWindows | null; winarm: InstallerOptionsWindows | null; linux: InstallerOptionsLinux | null; linuxArm64: InstallerOptionsLinux | null; linuxArm7: InstallerOptionsLinux | null; android: InstallerOptionsAndroid | null }

export type WindowsInstallScope = "User" | "Machine"

/**
 * This is exactly `Vec<(String, Vec<String>)>`
 */
export type HomeMapData = { inner: ([string, string[]])[] }

export type Prefs = { update: UpdateStrategy }

export type DownloadUrl = { installerType: InstallerFormat; asset: string; url: string }

export type Installer = { Architecture: string; InstallerType: string | null; InstallerLocale: string | null; InstallerUrl: string }

export type WingetApplication = { PackageIdentifier: string; PackageVersion: string; Publisher: string | null; PublisherUrl: string | null; Copyright: string | null; ShortDescription: string | null; Description: string | null; ReleaseNotes: string | null; PackageName: string; PackageUrl: string | null; License: string | null; LicenseUrl: string | null }

export type Splash = { hero: Hero; subhero: SubHero; third: Semi; fourth: Semi }

