import { Palette } from "std-widgets.slint";

export component ToolTip inherits Window {
    in property <string> text <=> text.text;
    in property <bool> user_is_hovering;
    property <bool> has_waited;
    z: 100;

    Rectangle {
        visible: has_waited && parent.user_is_hovering;
        background: Palette.alternate-background;
        border-color: Palette.border;
        border-width: 2px;
        border-radius: 0.5rem;
        text := Text {
            width: parent.width - 1rem;
            height: parent.height - 1rem;
            color: Palette.foreground;
            font-size: root.default-font-size * 0.9;
            horizontal-alignment: left;
            vertical-alignment: top;
            wrap: word-wrap;
        }
    }

    Timer {
        // Delay until tooltip appears.
        interval: 1s;
        running: parent.user_is_hovering || self.needs_resetting;
        // The resetting property allows the timer to reset to the default state
        // where it has not waited to show the tooltip yet. This is needed
        // because we can not listen to a "not hovering anymore" event. Thus, we
        // let the timer run a little bit longer and reset the state before
        // stopping `running`.
        property <bool> needs_resetting: false;
        triggered() => {
            if needs_resetting && !parent.user_is_hovering {
                // User is not hovering anymore.
                parent.has_waited = false;
                needs_resetting = false;
            } else {
                // User is hovering and waited, so tooltip can be shown.
                parent.has_waited = true;
                needs_resetting = true;
            }
        }
    }
}
